-- Première migration Flyway réellement exécutée (V1 est absorbée par le
-- baseline — voir spring.flyway.baseline-on-migrate dans application.properties).
-- Porte deux évolutions indépendantes :
--
--   1. Journal d'audit chaîné et horodaté (voir service.audit.AuditChainService) :
--      chaque entrée reçoit, de façon DIFFÉRÉE (job nocturne, jamais au moment
--      de l'écriture — voir la Javadoc d'AuditChainService pour la raison de
--      concurrence), l'empreinte SHA-256 d'elle-même chaînée à l'empreinte de
--      l'entrée précédente. audit_chain_seals conserve, pour chaque passage du
--      job, le jeton d'horodatage RFC 3161 scellant la dernière empreinte de
--      la chaîne à cet instant.
--
--   2. Sort final (voir entite.SortFinal) : chaque règle de rétention porte
--      désormais une décision CONSERVER / DETRUIRE / TRIER, qui gouverne ce
--      que fait DocumentRetentionService.purgeDocumentsCorbeille une fois le
--      délai de grâce de la corbeille écoulé (voir sa Javadoc mise à jour).
--      DEFAULT 'CONSERVER' explicite : backfill sûr des lignes existantes
--      (NOT NULL sur une table déjà peuplée) — aucune règle existante ne
--      devient éligible à une purge automatique sans décision explicite.

ALTER TABLE journal_audit ADD COLUMN IF NOT EXISTS chain_hash varchar(64);

CREATE TABLE IF NOT EXISTS audit_chain_seals
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dernier_entry_id    bigint,
    dernier_chain_hash  varchar(64),
    horodatage_token    bytea,
    horodatage_date     timestamptz,
    created_at          timestamptz NOT NULL
);

ALTER TABLE retentions ADD COLUMN IF NOT EXISTS sort_final varchar(20) NOT NULL DEFAULT 'CONSERVER';
