-- Plan de classement par UO (voir entite.PlanClassementNoeud) : arborescence
-- d'activités/fonctions (code + libellé) indépendante de l'organigramme, à
-- laquelle un type de document peut être rattaché — à tout moment, y compris
-- s'il a déjà des documents (colonne nullable : un type sans activité reste valide).

CREATE TABLE IF NOT EXISTS plan_classement_noeuds
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       varchar(30)  NOT NULL,
    libelle    varchar(150) NOT NULL,
    parent_id  bigint REFERENCES plan_classement_noeuds (id),
    uo_id      bigint       NOT NULL REFERENCES unites_organisationnelles (id),
    created_at timestamptz  NOT NULL,
    CONSTRAINT uk_plan_classement_code_uo UNIQUE (uo_id, code)
);

CREATE INDEX IF NOT EXISTS idx_plan_classement_uo ON plan_classement_noeuds (uo_id);

ALTER TABLE type_documents
    ADD COLUMN IF NOT EXISTS plan_classement_noeud_id bigint REFERENCES plan_classement_noeuds (id);

-- cible_type : contrainte CHECK générée par Hibernate à partir de l'enum AuditCible,
-- jamais resynchronisée automatiquement (absente de schema.sql) — nouvelle valeur ajoutée ici.
ALTER TABLE journal_audit DROP CONSTRAINT IF EXISTS journal_audit_cible_type_check;
ALTER TABLE journal_audit ADD CONSTRAINT journal_audit_cible_type_check CHECK (cible_type::text = ANY (ARRAY[
    'SESSION','UTILISATEUR','UNITE_ORGANISATIONNELLE','DOCUMENT','GROUPE_ACCES','TYPE_DOCUMENT','DOSSIER',
    'PHYSICAL_LOCATION','PLAN_CLASSEMENT'
]::text[]));
